<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Backtrack</AssemblyName>
    <RootNamespace>Backtrack</RootNamespace>
    
    <Version>0.3.14</Version>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.10.0" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="installer\**" />
    <EmbeddedResource Remove="installer\**" />
    <None Remove="installer\**" />
    <Compile Remove="backup\**" />
    <EmbeddedResource Remove="backup\**" />
    <None Remove="backup\**" />
    <Resource Include="Assets\logo.png" />
    <Resource Include="Assets\ilyambr.png" />
    <None Update="Assets\backtrack_tray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\app.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Audio\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Assets\Audio\*.wav" />
    
    <None Update="ThirdParty\ImDisk\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ThirdParty\FFmpeg\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    
    <Page Remove="Themes\Theme.*.xaml" />
    <None Include="Themes\Theme.*.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
